version: '3.8'

services:
    web:
        build: .
        container_name: webshop-web
        ports:
            - "8088:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_NAME: webshop_db
            DB_USER: webshopadmin
            DB_PASSWORD: '!webshopadmin2025'

    db:
        image: mysql:8.0
        container_name: webshop-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: webshop_db
            MYSQL_USER: webshopadmin
            MYSQL_PASSWORD: '!webshopadmin2025'
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
